id: vulnerability_handling_-_nexpose
version: -1
name: Vulnerability Handling - Nexpose
description: |-
  Manage vulnerability remediation using Nexpose data, and optionally enrich data with 3rd-party tools.

  Before you run this playbook, run the "Vulnerability Management - Nexpose (Job)" playbook.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: d127e66f-7ade-4b3c-8ba2-60857698d3ee
    type: start
    task:
      id: d127e66f-7ade-4b3c-8ba2-60857698d3ee
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 152.5,
          "y": 50
        }
      }
    note: false
    timertriggers: []
  "1":
    id: "1"
    taskid: 356935d6-9ca3-4c10-8518-ce37b1eb878b
    type: condition
    task:
      id: 356935d6-9ca3-4c10-8518-ce37b1eb878b
      version: -1
      name: Is Nexpose enabled?
      description: Verify that there's a valid instance of Nexpose enabled.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: Rapid7 Nexpose
                    ignorecase: true
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
                    ignorecase: true
                accessor: brand
            iscontext: true
    view: |-
      {
        "position": {
          "x": 152.5,
          "y": 195
        }
      }
    note: false
    timertriggers: []
  "2":
    id: "2"
    taskid: d0ea9b16-8e93-468a-8311-68805bbbe5e5
    type: title
    task:
      id: d0ea9b16-8e93-468a-8311-68805bbbe5e5
      version: -1
      name: Get vulnerability details from Nexpose
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
    timertriggers: []
  "3":
    id: "3"
    taskid: d553fc72-9bac-44e3-8c03-c295acd17f44
    type: title
    task:
      id: d553fc72-9bac-44e3-8c03-c295acd17f44
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 152.5,
          "y": 1855
        }
      }
    note: false
    timertriggers: []
  "4":
    id: "4"
    taskid: 8cff4db4-a188-42e4-84a4-d973febd4ea0
    type: regular
    task:
      id: 8cff4db4-a188-42e4-84a4-d973febd4ea0
      version: -1
      name: Get asset information
      description: Get asset metadata from Nexpose based on asset ID.
      script: Rapid7 Nexpose|||nexpose-get-asset
      type: regular
      iscommand: true
      brand: Rapid7 Nexpose
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      id:
        complex:
          root: incident
          accessor: assetid
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 515
        }
      }
    note: false
    timertriggers: []
  "5":
    id: "5"
    taskid: d17a5f7c-9bc4-4448-8b62-61efa02ca003
    type: regular
    task:
      id: d17a5f7c-9bc4-4448-8b62-61efa02ca003
      version: -1
      name: Get Vulnerability information
      description: Get vulnerability metadata from Nexpose based on vulnerability
        ID.
      script: Rapid7 Nexpose|||nexpose-get-asset-vulnerability
      type: regular
      iscommand: true
      brand: Rapid7 Nexpose
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      extend-context:
        simple: NexposeSeverity=severity
      id:
        complex:
          root: incident
          accessor: assetid
      vulnerabilityId:
        complex:
          root: incident
          accessor: vendorid
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 515
        }
      }
    note: false
    timertriggers: []
  "6":
    id: "6"
    taskid: 206d337a-bae4-409c-890f-6a9fc6c28a5f
    type: title
    task:
      id: 206d337a-bae4-409c-890f-6a9fc6c28a5f
      version: -1
      name: Enrich Entities
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
      - "8"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 690
        }
      }
    note: false
    timertriggers: []
  "7":
    id: "7"
    taskid: 4181e6a6-959a-472e-8e61-a254d9f5673e
    type: playbook
    task:
      id: 4181e6a6-959a-472e-8e61-a254d9f5673e
      version: -1
      name: CVE Enrichment - Generic
      playbookName: CVE Enrichment - Generic
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      CVE:
        complex:
          root: CVE
      GetReputation:
        simple: "True"
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 835
        }
      }
    note: false
    timertriggers: []
  "8":
    id: "8"
    taskid: b5894d35-8b97-4469-845b-4abdc660c56a
    type: playbook
    task:
      id: b5894d35-8b97-4469-845b-4abdc660c56a
      version: -1
      name: Endpoint Enrichment - Generic
      playbookName: Endpoint Enrichment - Generic
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      Hostname:
        complex:
          root: Endpoint
          accessor: HostName
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 480,
          "y": 835
        }
      }
    note: false
    timertriggers: []
  "9":
    id: "9"
    taskid: df0d00fa-f883-4c1b-816d-bacd8a184730
    type: regular
    task:
      id: df0d00fa-f883-4c1b-816d-bacd8a184730
      version: -1
      name: Set custom fields
      description: |-
        Set the information retrieved from Nexpose into the vulnerability incident custom fields:
        * Vulnerability Category
        * CVE
        * CVSS
        * Signature
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      addLabels: {}
      app: {}
      assetid: {}
      attachmentcount: {}
      attachmentextension: {}
      attachmenthash: {}
      attachmentid: {}
      attachmentitem: {}
      attachmentname: {}
      attachmentsize: {}
      attachmenttype: {}
      backupowner: {}
      bugtraq: {}
      customFields: {}
      cve:
        complex:
          root: Nexpose
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: Nexpose.Asset.Vulnerability.Id
                iscontext: true
              right:
                value:
                  simple: incident.vendorid
                iscontext: true
          accessor: Asset.Vulnerability.CVES
          transformers:
          - operator: uniq
          - operator: Stringify
      cvss:
        complex:
          root: Nexpose
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: Nexpose.Asset.Vulnerability.Id
                iscontext: true
              right:
                value:
                  simple: incident.vendorid
                iscontext: true
          accessor: Asset.Vulnerability.CVSSScore
          transformers:
          - operator: uniq
          - operator: Stringify
      daysbetweenreportcreation: {}
      dest: {}
      destntdomain: {}
      details: {}
      duration: {}
      emailbcc: {}
      emailbody: {}
      emailbodyformat: {}
      emailbodyhtml: {}
      emailcc: {}
      emailclientname: {}
      emailfrom: {}
      emailkeywords: {}
      emailmessageid: {}
      emailreceived: {}
      emailreplyto: {}
      emailreturnpath: {}
      emailsenderip: {}
      emailsize: {}
      emailsource: {}
      emailsubject: {}
      emailto: {}
      emailtocount: {}
      emailurlclicked: {}
      eventid: {}
      falses: {}
      fetchid: {}
      fetchtype: {}
      filehash: {}
      filename: {}
      filepath: {}
      id: {}
      important: {}
      importantfield: {}
      labels: {}
      malwarefamily: {}
      mdtest: {}
      myfield: {}
      name: {}
      occurred: {}
      owner: {}
      phase: {}
      replacePlaybook: {}
      reporteduser: {}
      roles: {}
      screenshot: {}
      screenshot2: {}
      selector: {}
      severity: {}
      signature:
        complex:
          root: Nexpose
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: Nexpose.Asset.Vulnerability.Id
                iscontext: true
              right:
                value:
                  simple: incident.vendorid
                iscontext: true
          accessor: Asset.Vulnerability.Title
          transformers:
          - operator: uniq
          - operator: Stringify
      single: {}
      single2: {}
      sla: {}
      source: {}
      src: {}
      srcntdomain: {}
      srcuser: {}
      systems: {}
      test: {}
      test2: {}
      testfield: {}
      timeassignedtolevel2: {}
      timefield1: {}
      timelevel1: {}
      type: {}
      user: {}
      username: {}
      vendorid: {}
      vendorproduct: {}
      vulnerabilitycategory:
        complex:
          root: Nexpose
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: Nexpose.Asset.Vulnerability.Id
                iscontext: true
              right:
                value:
                  simple: incident.vendorid
                iscontext: true
          accessor: Asset.Vulnerability.Categories
          transformers:
          - operator: uniq
          - operator: Stringify
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1010
        }
      }
    note: false
    timertriggers: []
  "10":
    id: "10"
    taskid: 351a2cef-df14-4458-8deb-ca7c26c1b89b
    type: title
    task:
      id: 351a2cef-df14-4458-8deb-ca7c26c1b89b
      version: -1
      name: Remediate
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1185
        }
      }
    note: false
    timertriggers: []
  "11":
    id: "11"
    taskid: 9a35d0f2-951b-4dfe-82ee-552342d5ed00
    type: playbook
    task:
      id: 9a35d0f2-951b-4dfe-82ee-552342d5ed00
      version: -1
      name: Calculate Severity - Generic
      description: |-
        Calculates and assign the incident severity based on the highest returned severity level from the following severity calculations:

        * Indicators DBotScore - Calculates the incident severity level according to the highest indicator DBotScore.
        * Critical assets - Determines if a critical assest is associated with the invesigation.
        * 3rd-party integrations - Calculates the incident severity level according to the methodology of a 3rd-party integration.

        NOTE: the new severity level overwrites the previous severity level even if the previous severity level was more severe.
      playbookName: Calculate Severity - Generic
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      Account:
        complex:
          root: Account
      DBotScore:
        complex:
          root: DBotScore
      Endpoint:
        complex:
          root: Endpoint
      NexposeSeverity:
        complex:
          root: NexposeSeverity
      QualysSeverity:
        complex:
          root: Qualys
          accessor: Severity
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1330
        }
      }
    note: false
    timertriggers: []
  "12":
    id: "12"
    taskid: a469ee6e-9487-4e94-828b-72a7c5f439d9
    type: regular
    task:
      id: a469ee6e-9487-4e94-828b-72a7c5f439d9
      version: -1
      name: 'Remediate the vulnerability '
      description: |
        Manually remediate the vulnerability using the remediation notes from Nexpose.
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1505
        }
      }
    note: false
    timertriggers: []
  "13":
    id: "13"
    taskid: 3cc3fdfa-3601-49c5-82e6-56dffc6ecda1
    type: regular
    task:
      id: 3cc3fdfa-3601-49c5-82e6-56dffc6ecda1
      version: -1
      name: Close investigation
      description: Close the investigation.
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      id: {}
      importantfield: {}
      test2: {}
      timefield1: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1680
        }
      }
    note: false
    timertriggers: []
system: true
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1870,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
